sudo: required
dist: trusty

install:
  - sudo apt-get update
  - sudo apt-get install -y qemu-utils qemu-system-x86

script:
  - wget https://download.freebsd.org/ftp/releases/VM-IMAGES/11.0-RELEASE/i386/Latest/FreeBSD-11.0-RELEASE-i386.qcow2.xz
  - unxz FreeBSD-11.0-RELEASE-i386.qcow2.xz
  - sudo modprobe nbd
  - sudo qemu-nbd --connect=/dev/nbd0 FreeBSD-11.0-RELEASE-i386.qcow2 &
  - while [[ ! -b /dev/nbd0p1 ]]; do sleep 1; done
  - sudo pkill qemu-ndb
