language: cpp
sudo: required
dist: trusty

install:
  - sudo apt-get update
  - sudo apt-get install -y qemu-utils qemu-system-x86
  - sudo apt-get install -y autoconf automake libfuse-dev e2fslibs-dev  # for ufs
  - git clone https://github.com/jblumsch/fuse-ufs2
  - (cd fuse-ufs2 && ./autogen.sh && ./configure && make -j`nproc` && sudo make install)

script:
  - wget https://download.freebsd.org/ftp/releases/VM-IMAGES/11.0-RELEASE/i386/Latest/FreeBSD-11.0-RELEASE-i386.qcow2.xz
  - unxz -v FreeBSD-11.0-RELEASE-i386.qcow2.xz
  - sudo modprobe nbd
  - sudo qemu-nbd --connect=/dev/nbd0 FreeBSD-11.0-RELEASE-i386.qcow2 &
  - while [[ ! -b /dev/nbd0p1 ]]; do sleep 1; done
  - sudo mkdir /mnt/fbsd
  - sudo /usr/local/bin/fuse-ufs /dev/nbd0p3 /mnt/fbsd -o rw
  - sudo ls -l /mnt/fbsd
  - echo 'auth required pam_unix.so nullok' | sudo tee /mnt/fbsd/etc/pam.d/sshd
  - echo 'ifconfig_vtnet0="inet 192.168.57.2/24"' | sudo tee /mnt/fbsd/etc/rc.conf
  - echo 'sshd_enable="YES"' | sudo tee -a /mnt/fbsd/etc/rc.conf
  - echo 'PermitRootLogin yes' | sudo tee -a /mnt/fbsd/etc/ssh/sshd_config
  - echo 'PermitEmptyPasswords yes' | sudo tee -a /mnt/fbsd/etc/ssh/sshd_config
  - sudo fusermount -u /mnt/fbsd
  - sudo /usr/local/bin/fuse-ufs /dev/nbd0p3 /mnt/fbsd
  - sudo ls -l /mnt/fbsd/etc/rc.conf
  - sudo cat /mnt/fbsd/etc/rc.conf
  - sudo fusermount -u /mnt/fbsd
  - sudo pkill qemu-nbd
  - sudo qemu-system-x86_64 -name FreeBSD -daemonize -display none -drive file=FreeBSD-11.0-RELEASE-i386.qcow2,if=virtio -m 1024 -smp cores=2 -netdev tap,id=controlnet,ifname=fbctrl,script=no,downscript=no -device virtio-net-pci,netdev=controlnet -rtc base=localtime,clock=host,driftfix=none
  - sudo ip a a 192.168.57.1/24 dev fbctrl
  - sudo ifconfig fbctrl up
  - ifconfig
  - for ((i=0; i<10; ++i)); do if ping -c4 192.168.57.2; then break; fi; sleep 10; done
  - sleep 30  # let ssh start
  - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@192.168.57.2 uname -a
