language: cpp
os: linux
sudo: required
dist: trusty
compiler: clang
script:
  - ls -l
  - clang++ -c -std=c++11 -fsanitize=thread -O1 -fPIE -o main.o main.cpp
  - clang++ -fsanitize=thread -pie main.o -o main
  - ldd main
  - ./main
