language: cpp
sudo: required
dist: trusty

install:
  - sudo apt-get update
  - sudo apt-get install -y python3-pip

script:
  - which python
  - pyenv versions
  - which pip3
  - pip3 --version
  - echo $PATH
  - /usr/bin/pip3 --version
  - /usr/bin/pip3 install coverage
