language: cpp
sudo: required
dist: trusty

script:
  - ls -l ~/virtualenv
  - ls -l /opt/python
  - find ~/virtualenv/python3.3/
  - source ~/virtualenv/python3.3/bin/activate
  - env
  - which python
  - pyenv versions
  - which pip3
  - pip3 --version
  - echo $PATH
  - /usr/bin/pip3 --version
  - /usr/bin/pip3 install coverage
