language: cpp
sudo: required
dist: trusty

install:
  - sudo apt-get update
  - sudo apt-get install -y qemu-utils qemu-system-x86
  - git clone https://github.com/jblumsch/fuse-ufs2
  - cd fuse-ufs2
  - ./configure && make && sudo make install
  - cd ..

script:
  - wget https://download.freebsd.org/ftp/releases/VM-IMAGES/11.0-RELEASE/i386/Latest/FreeBSD-11.0-RELEASE-i386.qcow2.xz
  - unxz FreeBSD-11.0-RELEASE-i386.qcow2.xz
  - sudo modprobe nbd
  - sudo qemu-nbd --connect=/dev/nbd0 FreeBSD-11.0-RELEASE-i386.qcow2 &
  - while [[ ! -b /dev/nbd0p1 ]]; do sleep 1; done
  - sudo mkdir /mnt/fbsd
  - sudo /usr/local/bin/fuse-ufs /dev/nbd0p1 /mnt/fbsd
  - ls -l /mnt/fbsd
  - fusermount -u /mnt/fbsd
  - sudo /usr/local/bin/fuse-ufs /dev/nbd0p3 /mnt/fbsd
  - ls -l /mnt/fbsd
  - fusermount -u /mnt/fbsd
  - sudo pkill qemu-nbd
    # rc.conf
    #ifconfig_vtnet0_ipv6="inet6 fd1a:cd75:f79f:7c72::1 prefixlen 64"
    #sshd_enable="YES"
    # pam.d/sshd
    #auth required pam_unix.so nullok
