language: cpp
os: linux
sudo: required
dist: trusty
compiler: clang
script:
  - clang++ -std=c++11 -fsanitize=thread -O1 -fPIE main.cpp -O main.o
  - clang++ -fsanitize=thread -pie main.o -ldl -lpthread -lssl -lcrypto -lz -licuuc -licudata -lboost_locale -O main
  - ldd main
  - ./main
