language: cpp
os: linux
sudo: required
dist: trusty
compiler: clang
install:
  - sudo apt-get update
  - sudo apt-get install -y libboost-locale-dev
script:
  - ls -l
  - clang++ -c -std=c++11 -fsanitize=thread -O1 -fPIE -o main.o main.cpp
  - clang++ -fsanitize=thread -pie main.o -ldl -lpthread -lssl -lcrypto -lz -licuuc -licudata -o main
  - ldd main
  - ./main
