language: cpp
sudo: required
dist: trusty

install:
  - sudo apt-get update

script:
  - which pip3
  - pip3 --version
  - echo $PATH
  - ls -l /opt/python
  - which easy_install3
  - easy_install3 --version
  - easy_install3 coverage
