language: cpp
sudo: required
dist: trusty

install:
  - sudo apt-get update
  - sudo apt-get install -y qemu-utils qemu-system-x86
  - sudo apt-get install -y autoconf automake libfuse-dev e2fslibs-dev  # for ufs
  - git clone https://github.com/jblumsch/fuse-ufs2
  - (cd fuse-ufs2 && ./autogen.sh && ./configure && make -j`nproc` && sudo make install)

script:
  - wget https://download.freebsd.org/ftp/releases/VM-IMAGES/11.0-RELEASE/i386/Latest/FreeBSD-11.0-RELEASE-i386.qcow2.xz
  - unxz -v FreeBSD-11.0-RELEASE-i386.qcow2.xz
  - sudo modprobe nbd
  - sudo qemu-nbd --connect=/dev/nbd0 FreeBSD-11.0-RELEASE-i386.qcow2 &
  - while [[ ! -b /dev/nbd0p1 ]]; do sleep 1; done
  - sudo mkdir /mnt/fbsd
  - sudo /usr/local/bin/fuse-ufs /dev/nbd0p3 /mnt/fbsd -o rw
  - sudo ls -l /mnt/fbsd
  - echo 'auth required pam_unix.so nullok' | sudo tee /mnt/fbsd/etc/pam.d/sshd
  - echo 'ifconfig_vtnet0_ipv6="inet6 fd1a:cd75:f79f:7c72::1 prefixlen 64"' | sudo tee /mnt/fbsd/etc/rc.conf
  - echo 'sshd_enable="YES"' | sudo tee -a /mnt/fbsd/etc/rc.conf
  - echo 'PermitRootLogin yes' | sudo tee -a /mnt/fbsd/etc/ssh/ssd_config
  - echo 'PermitEmptyPasswords yes' | sudo tee -a /mnt/fbsd/etc/ssh/ssd_config
  - sudo fusermount -u /mnt/fbsd
  - sudo pkill qemu-nbd
  - sudo qemu-system-x86_64 -name FreeBSD -daemonize -display none -drive file=FreeBSD-11.0-RELEASE-i386.qcow2,if=virtio -m 512 -smp cores=2 -netdev tap,id=controlnet,ifname=fbctrl,script=no,downscript=no -device virtio-net-pci,netdev=controlnet
  - ifconfig -a
  - sleep 10
  - ifconfig -a
  - sudo ip a a fd1a:cd75:f79f:7c72::2/64 dev fbctrl
  - sudo ifconfig fbctrl up
  - ping6 -c 200 fd1a:cd75:f79f:7c72::1 || true
  - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@fd1a:cd75:f79f:7c72::1 uname -a
