language: cpp
sudo: required
dist: trusty

script:
  - find /opt/python/3.5.2
  - ls -l ~/virtualenv
  - source ~/virtualenv/python3.3/bin/activate
  - "echo pkg-config path: [$PKG_CONFIG_PATH]"
  - which python
  - pyenv versions
  - which pip3
  - pip3 --version
  - echo $PATH
  - /usr/bin/pip3 --version
  - /usr/bin/pip3 install coverage
